import { operatorToolMetadata } from './tools/registry.js'

export const OPERATOR_CAPABILITY_VERSION = 1

export function buildCapabilityManifest() {
  return {
    version: OPERATOR_CAPABILITY_VERSION,
    generatedFrom: 'lib/operator-agent/tools/registry.js',
    agent: { id: 'operator-agent', displayName: 'Maggie', role: 'Operator', runtime: 'frontier' },
    tools: operatorToolMetadata(),
  }
}

export function renderCapabilityMarkdown(manifest = buildCapabilityManifest()) {
  const lines = [
    '# Operator Agent Capabilities', '',
    '> Generated by `scripts/operator-agent-manifest.mjs` from the live tool registry. Do not hand-edit.', '',
    `Agent: **${manifest.agent.displayName}** (${manifest.agent.id}) · Role: **${manifest.agent.role}** · Runtime: **${manifest.agent.runtime}**`, '',
    '| Tool | Purpose | Inputs | Side effects | Cost | Screen |',
    '| --- | --- | --- | --- | --- | --- |',
  ]
  for (const item of manifest.tools) {
    const inputs = item.inputs.map(name => item.requiredInputs.includes(name) ? `${name}*` : name).join(', ') || 'none'
    lines.push(`| \`${item.name}\` | ${item.purpose} | ${inputs} | ${item.sideEffects} | ${item.cost.label} | ${item.screen} |`)
  }
  lines.push('', '*Required inputs are marked with `*`. The JSON companion is the runtime source used to build Maggie\'s system prompt.*', '')
  return lines.join('\n')
}
